### ISSUE TITLE
where is your code？

### ISSUE THREAD

**Issue by my462** [finger-monkey/ReID_Adversarial_Defense#1]

**Comment by finger-monkey** [comment]
Hi, the code was removed earlier for some reason. I will update it. By the way, the new version of my paper will be released later, and the new code will be updated again.

**Comment by my462** [comment]
thx for your rely. btw, in your LGPR method, do you still keep random erase augmentation? If so, how do you arrange them in the augmentation part. This is mainly the reason I want to read your code canse in your paper you did not provide all the augmentation you used.

**Comment by my462** [comment]
I see your ablation exps for cross-domain part and I want to know if you use REA before that part, that is market/msmt/duke.

**Comment by finger-monkey** [comment]
The exps used default configuration of the baseline code(Random Erasing is one of default config ), under this condition to add LGPR or GGPR.  About cross-domain exps, Random Erasing has a negative effect on cross-domian performance, GGPR or LGPR do not have these problems. 
I used REA before that part as a default config, that is market/msmt/duke exps.

**Comment by finger-monkey** [comment]
By the way, the following paper is updated mainly for  the part of adversarial attack and defense.

**Comment by my462** [comment]
> By the way, the following paper is updated mainly for the part of adversarial attack and defense.

good job and good luck dude

**Comment by finger-monkey** [comment]
Thank you.

**Comment by finger-monkey** [comment]
The latest version of the paper can be viewed at (http://arxiv.org/abs/2111.09571)
